---
kind: Service
apiVersion: v1
metadata:
  name: lab-app-java-service
  namespace: lab
  labels:
    app: lab-app-java
    env: dev
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8080
  selector:
    app: lab-app-java
  type: LoadBalancer
