---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lab-app-java
  namespace: default
  labels:
    app: lab-app-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-app-java
  template:
    metadata:
      labels:
        app: lab-app-java
    spec:
      containers:
      - name: lab-app-java
        image: registry.docker-registry.svc:5001/prd/lab-app-java:latest
        ports:
        - containerPort: 8080
          protocol: TCP